version: '3.8'

services:
  # Сервис для приложения NestJS
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CryptogramWebDocker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:latest
    container_name: CryptogramDBDocker
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} -h localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
